name = "item-info-worker"
type = "javascript"
account_id = "277325a6f20c9881d7146134c7224e9e"
workers_dev = true
compatibility_date = "2024-05-08"
main = "src/index.js"

kv_namespaces = [
  { binding = "ITEMS_DATA", id = "f06e67052aef4d8c840ad245a8052931" }
]